### ISSUE TITLE
h5ad anndata object obs do not show in cellxgene explorer

### ISSUE THREAD

**Issue by brainfo** [chanzuckerberg/cellxgene-documentation#10]
My h5ad anndata object summary:

```
AnnData object with n_obs × n_vars = 42414 × 25278
    obs: 'group', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'leiden', 'merged', 'coarse'
    var: 'gene_ids', 'feature_types', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'log1p', 'hvg', 'pca', 'neighbors', 'umap', 'tsne', 'group_colors', 'leiden', 'leiden_colors', 'rank_genes_groups', 'merged_colors', 'coarse_colors'
    obsm: 'X_pca', 'X_umap', 'X_tsne'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'
```

On the explorer, there are no 'leiden', 'merged', 'coarse' categories. 
For example, the adata.obs['leiden]: 
```
Name: leiden, Length: 42414, dtype: category
Categories (15, object): ['0', '1', '2', '3', ..., '11', '12', '13', '14']
```
The dtype is the same as adata.obs['group'], I just don't know why leiden category does not show up in the explorer.

I cannot create a new category either, since there's no assignment.
![image](https://user-images.githubusercontent.com/11832080/154352169-dc841661-5622-4ab7-853f-d52166d5e1cf.png)
How could I present all obs annotation on the explorer?

Thanks!

**Comment by MaximilianLombardo** [comment]
Hey @brainfo were you able to solve the issue on your own?

**Comment by brainfo** [comment]
> Hey @brainfo were you able to solve the issue on your own?

Yes. Thanks!!

**Comment by MaximilianLombardo** [comment]
great, thanks for the update!
