### ISSUE TITLE
deposit cellxgene using nginx

### ISSUE THREAD

**Issue by brainfo** [chanzuckerberg/cellxgene-documentation#11]
As in your readme, `First, the flask application which is deployed on your server (found in the ‘prep your project’ section of the linked article) should be cellxgene with an appropriate wsgi.py file added as described in the article. `
I don't know how to modify this to make it run cellxgene
```
from myapp import create_app

app = create_app()

if __name__ == "__main__":
    app.run(host='0.0.0.0')
```
Any help?
Thanks!

**Comment by MaximilianLombardo** [comment]
Hey @brainfo - I think this might have been addressed in this [czi science slack thread](https://czi-sci.slack.com/archives/CCTA8DF1T/p1645727860163309)

For completeness in this github discussion - check out this example of [self-hosting cellxgene using nginx](https://github.com/chanzuckerberg/cellxgene-documentation/blob/main/desktop/self-hosting/nginx.md)

Also, it is worth noting that the cellxgene team does not provide dedicated help for self-hosting, so it is likely we won't be able to provide "official" guidance past this point - but hopefully this resource should get you started!

**Comment by brainfo** [comment]
已收到，谢谢。
