### ISSUE TITLE
Sanger UK Maternal-Fetal Interface data download

### ISSUE THREAD

**Issue by elzerac** [chanzuckerberg/cellxgene-documentation#8]
Hello! 

I am looking to download the anndata file for this cellxgene project: 

https://maternal-fetal-interface.cellgeni.sanger.ac.uk/

I don't see it in the data portal, but I see that it is using the cellxgene interface. Is there anyway to download the .h5ad file from this project? 

Thank you! 

Elze

**Comment by MaximilianLombardo** [comment]
Hey @elzerac !

The link you posted is a different implementation of hosted cellxgene desktop explorer (it is not maintained by the CZI team and the dataset is not hosted on [https://cellxgene.cziscience.com/](https://cellxgene.cziscience.com/) ). You could try reaching out to the [cellgeni group](cellxgene.cziscience.com) about your question.

Thanks!
